# Use the latest 2.1 version of CircleCI pipeline process engine. See httpscircleci.comdocs2.0configuration-reference
version 2.1
# Use a package of configuration called an orb.
orbs
  # Declare a dependency on the welcome-orb
  welcome circleciwelcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows
  # Name the workflow welcome
  welcome
    # Run the welcomerun job in its own container
    jobs
      - welcomerun